apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-price-prediction-deployment
  namespace: home-price-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: pmshrik/flask-app-home-price-prediction
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: home-price-prediction
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007